export const drinkList = [
  {
    id: 1,
    image: "/image/88rising miring.png",
    name: "Rainbow Drink",
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Esse, nobis?",
    price: "0.0015",
  },
  {
    id: 2,
    image: "/image/boba miring.png",
    name: "Lovers Drink",
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Esse, nobis?",
    price: "0.0014",
  },
  {
    id: 3,
    image: "/image/cheese miring.png",
    name: "Lemonade Stardust",
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Esse, nobis?",
    price: "0.00096",
  },
  {
    id: 4,
    image: "/image/rainbow miring.png",
    name: "Unicorns Drink",
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Esse, nobis?",
    price: "0.0014",
  },
  {
    id: 5,
    image: "/image/boba miring.png",
    name: "Lovers Drink",
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Esse, nobis?",
    price: "0.0014",
  },
  {
    id: 6,
    image: "/image/cheese miring.png",
    name: "Lemonade Stardust",
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Esse, nobis?",
    price: "0.00096",
  },
  {
    id: 7,
    image: "/image/rainbow miring.png",
    name: "Unicorns Drink",
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Esse, nobis?",
    price: "0.0014",
  },
  {
    id: 8,
    image: "/image/88rising miring.png",
    name: "Rainbow Drink",
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Esse, nobis?",
    price: "0.0015",
  },
];
